language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t abfmcdr/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true abfmcdr/docker-react npm run test -- --coverage